// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDD5a1A59-tCMH_7X14AluA9gqtBcIh6Uo",
    authDomain: "myflutterapp-f3425.firebaseapp.com",
    projectId: "myflutterapp-f3425",
    storageBucket: "myflutterapp-f3425.firebasestorage.app",
    messagingSenderId: "446034822686",
    appId: "1:446034822686:web:d83fba5c818737e5d5500f",
    measurementId: "G-3ZRJG8QTBN",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdJ-UTW_qHENKHPEB_5k7VU64HkIUPh4',
    appId: '1:446034822686:android:315fa44c95b2bf17d5500f',
    messagingSenderId: '446034822686',
    projectId: 'myflutterapp-f3425',
    storageBucket: 'myflutterapp-f3425.firebasestorage.app',
  );
}
